# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "torpedo"
  s.version = "2.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Prince"]
  s.date = "2013-10-02"
  s.description = "Fast integration tests for OpenStack."
  s.email = "dprince@redhat.com"
  s.executables = ["torpedo"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/torpedo",
    "lib/torpedo.rb",
    "lib/torpedo/cleanup.rb",
    "lib/torpedo/compute/flavors.rb",
    "lib/torpedo/compute/helper.rb",
    "lib/torpedo/compute/images.rb",
    "lib/torpedo/compute/keypairs.rb",
    "lib/torpedo/compute/limits.rb",
    "lib/torpedo/compute/servers.rb",
    "lib/torpedo/config.rb",
    "lib/torpedo/metering/helper.rb",
    "lib/torpedo/metering/meters.rb",
    "lib/torpedo/net_util.rb",
    "lib/torpedo/orchestration/helper.rb",
    "lib/torpedo/orchestration/stacks.rb",
    "lib/torpedo/orchestration/test_server.hot",
    "lib/torpedo/volume/helper.rb",
    "lib/torpedo/volume/volumes.rb",
    "test/helper.rb",
    "torpedo.gemspec"
  ]
  s.homepage = "http://github.com/dprince/torpedo"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Fire when ready. Fast Ruby integration tests for OpenStack."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<test-unit>, [">= 0"])
      s.add_runtime_dependency(%q<fog>, [">= 0"])
      s.add_runtime_dependency(%q<net-ssh>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<fog>, [">= 0"])
      s.add_dependency(%q<net-ssh>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<fog>, [">= 0"])
    s.add_dependency(%q<net-ssh>, [">= 0"])
  end
end

